plugins {
    // Plugins automatically generated by MLGradleWriter.kt
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
}

android {
    namespace = "com.feather.calculator"
    compileSdk = 36

    defaultConfig {
        applicationId = "com.feather.calculator"
        minSdk = 21
        targetSdk = 34
        versionCode = 1
        versionName = "1.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    buildFeatures {
        viewBinding = true
    }

    // --- Advanced Build Type Configuration ---
    buildTypes {
        // 1. **Optimized Release Build (Fully Compressed APK)**
        release {
            isMinifyEnabled = true
            isShrinkResources = true
            
            // FIX 1: Using double quotes for string literals
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"), 
                "proguard-rules.pro"
            )
            
            isDebuggable = false
            // Optional: Add a signingConfig here for real-world release
            // signingConfig = signingConfigs.getByName("release") 
        }

        // 2. **Fast Debug Build**
        debug {
            isMinifyEnabled = false
            isShrinkResources = false
            
            // FIX 2: Correct Kotlin DSL syntax to access the debug signing config
            signingConfig = signingConfigs.getByName("debug")
        }
    }
    // --- End of Advanced Build Type Configuration ---

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlin {
        compilerOptions {
            jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.fromTarget("17"))
        }
    }
}

dependencies {
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.appcompat)
    implementation(libs.material)
    implementation(libs.androidx.constraintlayout)
}
